More WIP multilib testing

diff --git a/patches/crosstool-ng/0002-Fix-glibc-and-eglibc-multilib-build.patch b/patches/crosstool-ng/0002-Fix-glibc-and-eglibc-multilib-build.patch
--- a/patches/crosstool-ng/0002-Fix-glibc-and-eglibc-multilib-build.patch
+++ b/patches/crosstool-ng/0002-Fix-glibc-and-eglibc-multilib-build.patch
@@ -1,4 +1,4 @@
-From aa1327c710c5004a69b010eed2332b2e32798cb1 Mon Sep 17 00:00:00 2001
+From 1bc6abb39c19a35a32473789933e218d74df819d Mon Sep 17 00:00:00 2001
 From: Ray Donnelly <mingw.android@gmail.com>
 Date: Wed, 20 Nov 2013 21:19:23 +0000
 Subject: [PATCH 2/5] Fix glibc and eglibc multilib build
@@ -16,11 +16,15 @@ made if CT_MULTILIB=n
 
 Also, the dummy libc.so is made using the right
 extra_cflags so that it's of the correct arch.
+
+Specify --with-binutils= for glibc
+
+.. (WIP) fail deliberately.
 ---
  scripts/build/cc/100-gcc.sh               |  1 +
- scripts/build/libc/glibc-eglibc.sh-common | 31 +++++++++++++++++++++++++------
- scripts/crosstool-NG.sh.in                | 25 ++++++++++++++-----------
- 3 files changed, 40 insertions(+), 17 deletions(-)
+ scripts/build/libc/glibc-eglibc.sh-common | 35 +++++++++++++++++++++++++------
+ scripts/crosstool-NG.sh.in                | 25 ++++++++++++----------
+ 3 files changed, 44 insertions(+), 17 deletions(-)
 
 diff --git a/scripts/build/cc/100-gcc.sh b/scripts/build/cc/100-gcc.sh
 index ede8cc5..f2ee583 100644
@@ -35,7 +39,7 @@ index ede8cc5..f2ee583 100644
          extra_config+=("--disable-multilib")
      fi
 diff --git a/scripts/build/libc/glibc-eglibc.sh-common b/scripts/build/libc/glibc-eglibc.sh-common
-index b9c55cb..b26fff6 100644
+index b9c55cb..ac89723 100644
 --- a/scripts/build/libc/glibc-eglibc.sh-common
 +++ b/scripts/build/libc/glibc-eglibc.sh-common
 @@ -76,6 +76,9 @@ do_libc_backend() {
@@ -81,7 +85,7 @@ index b9c55cb..b26fff6 100644
              # glibc install its files in ${extra_dir}/{usr/,}lib
              # while gcc expects them in {,usr/}lib/${extra_dir}.
              # Prepare some symlinks so glibc installs in fact in
-@@ -140,10 +155,11 @@ do_libc_backend() {
+@@ -140,12 +155,16 @@ do_libc_backend() {
  
          CT_mkdir_pushd "${CT_BUILD_DIR}/build-libc-${libc_mode}${extra_dir//\//_}"
  
@@ -96,8 +100,13 @@ index b9c55cb..b26fff6 100644
 +                             libc_triplet="${multi_arch}${rest_of_triplet}"     \
                               libc_full="${libc_full}"
  
++        CT_DoLog ERROR "Failing deliberately after libc-startfiles for comparison purposes"
++        exit 1
++
          CT_Popd
-@@ -180,6 +196,7 @@ do_libc_backend() {
+ 
+         if [ "${multi_dir}" != "." ]; then
+@@ -180,6 +199,7 @@ do_libc_backend() {
  #   Parameter           : Definition                            : Type      : Default
  #   libc_headers        : Build libc headers                    : bool      : n
  #   libc_startfiles     : Build libc start-files                : bool      : n
@@ -105,7 +114,7 @@ index b9c55cb..b26fff6 100644
  #   libc_full           : Build full libc                       : bool      : n
  #   extra_flags         : Extra CFLAGS to use (for multilib)    : string    : (empty)
  #   extra_dir           : Extra subdir for multilib             : string    : (empty)
-@@ -196,6 +213,7 @@ do_libc_backend_once() {
+@@ -196,6 +216,7 @@ do_libc_backend_once() {
      local glibc_cflags
      local float_extra
      local endian_extra
@@ -113,7 +122,7 @@ index b9c55cb..b26fff6 100644
      local arg
  
      for arg in "$@"; do
-@@ -354,7 +372,7 @@ do_libc_backend_once() {
+@@ -354,12 +375,13 @@ do_libc_backend_once() {
      "${src_dir}/configure"                                          \
          --prefix=/usr                                               \
          --build=${CT_BUILD}                                         \
@@ -122,7 +131,13 @@ index b9c55cb..b26fff6 100644
          --cache-file="$(pwd)/config.cache"                          \
          --without-cvs                                               \
          --disable-profile                                           \
-@@ -438,7 +456,8 @@ do_libc_backend_once() {
+         --without-gd                                                \
+         --with-headers="${CT_HEADERS_DIR}"                          \
++        --with-binutils=${CT_PREFIX_DIR}/bin                        \
+         "${extra_config[@]}"                                        \
+         "${CT_LIBC_GLIBC_EXTRA_CONFIG_ARRAY[@]}"
+ 
+@@ -438,7 +460,8 @@ do_libc_backend_once() {
              # However, since we will never actually execute its code,
              # it doesn't matter what it contains.  So, treating '/dev/null'
              # as a C source file, we produce a dummy 'libc.so' in one step
@@ -174,5 +189,5 @@ index 3c98b8c..5a24439 100644
      # Determine build system if not set by the user
      if [ -z "${CT_BUILD}" ]; then
 -- 
-1.8.4.3
+1.8.4.2
 
